// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOStDuhYu5Is-AD97r5iwSZiHHfb74Rw',
    appId: '1:83684917538:web:6d1284ade3ded3fc5c257b',
    messagingSenderId: '83684917538',
    projectId: 'proyectojenni-47a1f',
    authDomain: 'proyectojenni-47a1f.firebaseapp.com',
    storageBucket: 'proyectojenni-47a1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHqoV1njsWb5Ij2G_0HMht1Yo3g-rRjU4',
    appId: '1:83684917538:android:ff0a9802be7e941c5c257b',
    messagingSenderId: '83684917538',
    projectId: 'proyectojenni-47a1f',
    storageBucket: 'proyectojenni-47a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cTCRA-WproZLpT9Y7dQAIhyqmMtCgrs',
    appId: '1:83684917538:ios:5f111ae8450ab6d15c257b',
    messagingSenderId: '83684917538',
    projectId: 'proyectojenni-47a1f',
    storageBucket: 'proyectojenni-47a1f.appspot.com',
    iosBundleId: 'com.example.appjenni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4cTCRA-WproZLpT9Y7dQAIhyqmMtCgrs',
    appId: '1:83684917538:ios:5f111ae8450ab6d15c257b',
    messagingSenderId: '83684917538',
    projectId: 'proyectojenni-47a1f',
    storageBucket: 'proyectojenni-47a1f.appspot.com',
    iosBundleId: 'com.example.appjenni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVOStDuhYu5Is-AD97r5iwSZiHHfb74Rw',
    appId: '1:83684917538:web:3488907237f590e35c257b',
    messagingSenderId: '83684917538',
    projectId: 'proyectojenni-47a1f',
    authDomain: 'proyectojenni-47a1f.firebaseapp.com',
    storageBucket: 'proyectojenni-47a1f.appspot.com',
  );
}
